# Generated by Django 6.0.3 on 2026-03-25 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_document_owner_document_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='content_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='editor.document'),
        ),
    ]
